//
//  Star.swift
//  KragerChat
//
//  Created by Matthew Krager on 3/7/19.
//  Copyright © 2019 Matthew Krager. All rights reserved.
//

import UIKit

class Star: UIView {
    
    convenience init() {
        self.init(frame: .zero)
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        backgroundColor = .clear
        clipsToBounds = false
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    // Only override draw() if you perform custom drawing.
    // An empty implementation adversely affects performance during animation.
    override func draw(_ rect: CGRect) {
        super.draw(rect)
        
        // Paint Code Star Drawing
        // This code was generated by Trial version of PaintCode, therefore cannot be used for commercial purposes.
        // http://www.paintcodeapp.com
        
        //// Color Declarations
        let color2 = UIColor(red: 0.988, green: 1.000, blue: 0.000, alpha: 0.225)
        let color = UIColor(red: 0.923, green: 0.938, blue: 0.000, alpha: 1.000)
        
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 38.5, y: 6.5))
        bezierPath.addCurve(to: CGPoint(x: 0.5, y: 3.5), controlPoint1: CGPoint(x: 8.5, y: -5.5), controlPoint2: CGPoint(x: 0.5, y: 3.5))
        bezierPath.addLine(to: CGPoint(x: 1, y: 11))
        bezierPath.addCurve(to: CGPoint(x: 7, y: 11), controlPoint1: CGPoint(x: 1, y: 11), controlPoint2: CGPoint(x: 0, y: 18))
        bezierPath.addCurve(to: CGPoint(x: 34.5, y: 17.5), controlPoint1: CGPoint(x: 14, y: 4), controlPoint2: CGPoint(x: 34.5, y: 17.5))
        color2.setFill()
        bezierPath.fill()
        
        
        //// Star Drawing
        let starPath = UIBezierPath()
        starPath.move(to: CGPoint(x: 42, y: 0))
        starPath.addLine(to: CGPoint(x: 47.29, y: 7.72))
        starPath.addLine(to: CGPoint(x: 56.27, y: 10.36))
        starPath.addLine(to: CGPoint(x: 50.56, y: 17.78))
        starPath.addLine(to: CGPoint(x: 50.82, y: 27.14))
        starPath.addLine(to: CGPoint(x: 42, y: 24))
        starPath.addLine(to: CGPoint(x: 33.18, y: 27.14))
        starPath.addLine(to: CGPoint(x: 33.44, y: 17.78))
        starPath.addLine(to: CGPoint(x: 27.73, y: 10.36))
        starPath.addLine(to: CGPoint(x: 36.71, y: 7.72))
        starPath.close()
        color.setFill()
        starPath.fill()
    }
}
